### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by maximetinu** [Guillergood/CCProject#1]
**STEPS TO RECREATE**
- Go to the repo page
- Read the description

**EXPECTED RESULT**
Proyecto de la asignatura Cloud Computing I del máster Universitario de la Universidad de Granada

**ACTUAL RESULT**
Proyecto de la asignatura Cloud Computing I del mAster Universitario de la Universidad de Granada

**SUGGESTED FIX**
Replace "A" by "á"

**Comment by Guillergood** [comment]
Thanks very much, my dear friend :D

**Comment by Guillergood** [comment]
It is solved now.
